name: "Retest"
description: 'Re-run failed GitHub Workflow runs on PRs by commenting "/retest".'
author: "yuluo"
inputs:
  token:
    description: >
      GitHub token used to create and remove comments. By default, this uses the
      repository token provided by GitHub Actions. You can customize the user by
      replacing this token with a user token which has write-access to your
      repository. Note that the token will be accessible to all repository
      collaborators.
    default: ${{ github.token }}
  comment-id:
    description: >-
      ID of comment for response
    required: true
    type: number
    default: 123
  pr-url:
    description: >-
      URL to fetch PR information
    required: true
    default: "/pulls/123"
  args:
    description: >-
      Args passed to command (not currently used)

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.comment-id }}
    - ${{ inputs.pr-url }}
    - ${{ inputs.args }}
