name: Retest Action on PR Comment

on:
  issue_comment:
    types: [created]

permissions:
  contents: read

jobs:
  retest:
    name: Retest
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
      actions: write
    steps:
      - uses: yuluo-yx/gh-retest@2024.04.22
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
